"""Delete dummy field

Revision ID: eb533997f261
Revises: 33a8d5aa0831
Create Date: 2025-10-23 13:54:25.038597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb533997f261'
down_revision: Union[str, Sequence[str], None] = '33a8d5aa0831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deskbooking', 'dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deskbooking', sa.Column('dummy', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
